# Generated by Django 3.0.7 on 2021-09-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='products_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
